engager {
  http {
    host = "0.0.0.0"
    host = ${?HTTP_HOST}
    port = 8080
    port = ${?HTTP_PORT}
  }

  kafka {
    bootstrap-servers = "localhost:9092"
    bootstrap-servers = ${?KAFKA_BOOTSTRAP_SERVERS}
    events-topic = "user-events"
    group-id = "engager-consumer"
  }

  elasticsearch {
    host = "localhost"
    host = ${?ES_HOST}
    port = 9200
    port = ${?ES_PORT}
    events-index = "events"
    profiles-index = "user-profiles"
  }

  postgres {
    url = "jdbc:postgresql://localhost:5432/engager"
    url = ${?POSTGRES_URL}
    user = "engager"
    user = ${?POSTGRES_USER}
    password = "engager"
    password = ${?POSTGRES_PASSWORD}
    driver = "org.postgresql.Driver"
  }
}

akka {
  loggers = ["akka.event.slf4j.Slf4jLogger"]
  loglevel = "INFO"
  logging-filter = "akka.event.slf4j.Slf4jLoggingFilter"

  kafka {
    consumer {
      kafka-clients {
        auto.offset.reset = "earliest"
      }
    }
    producer {
      kafka-clients {
        acks = "all"
      }
    }
  }
}
